cbm – CABLE
cbm Subroutine
76 statements
Source File
public subroutine cbm(ktau, dels, air, bgc, canopy, met, bal, rad, rough, soil, ssnow, sum_flux, veg, climate, xk, c1, rhoch)
Uses
cable_carbon_module
cable_phys_constants_mod
cable_other_constants_mod
snow_aging_mod
casadimension
cable_gw_hydro_module
cable_common_module
cable_canopy_module
cbl_soil_snow_main_module
cable_air_module
cable_math_constants_mod
cable_def_types_mod
cbl_albedo_mod
sli_main_mod
cbl_masks_mod
cbl_init_radiation_module
cable_roughness_module
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ktau
real, intent(in) :: dels
type(air_type), intent(inout) :: air
type(bgc_pool_type), intent(inout) :: bgc
type(canopy_type), intent(inout) :: canopy
type(met_type), intent(inout) :: met
type(balances_type), intent(inout) :: bal
type(radiation_type), intent(inout) :: rad
type(roughness_type), intent(inout) :: rough
type(soil_parameter_type), intent(inout) :: soil
type(soil_snow_type), intent(inout) :: ssnow
type(sum_flux_type), intent(inout) :: sum_flux
type(veg_parameter_type), intent(inout) :: veg
type(climate_type), intent(in) :: climate
real :: xk(mp,nrb)
real :: c1(mp,nrb)
real :: rhoch(mp,nrb)
Calls
Called by
Contents
None
Call graph
cbm calls ruff_resist, fveg_mask, snow_aging, fsunlit_veg_mask, define_canopy, plantcarb, carbon_pl, define_air, fsunlit_mask, init_radiation, albedo, soil_snow, soilcarb
mpidrv_worker calls cbm
cable_offline_driver calls cbm
mpi_driver calls mpidrv_worker