create_landuse_cable_restart – CABLE
create_landuse_cable_restart Subroutine
204 statements
Source File
subroutine create_landuse_cable_restart(logn, dels, ktau, soil, mpx, lucmp, cstart, cend, nap)
Uses
cable_abort_module
cable_common_module
landuse_variable
cable_def_types_mod
cable_IO_vars_module
cable_write_module
netcdf
cable_checks_module
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: logn
real, intent(in) :: dels
integer, intent(in) :: ktau
type(soil_parameter_type) :: soil
integer, intent(in) :: mpx
type(landuse_mp) :: lucmp
integer, intent(in), DIMENSION(mland) :: cstart
integer, intent(in), DIMENSION(mland) :: cend
integer, intent(in), DIMENSION(mland) :: nap
Calls
Called by
Contents
None
Call graph
create_landuse_cable_restart calls nf90_create, nf90_enddef, nc_abort, nf90_redef, nf90_def_var, nf90_put_var, write_ovar, nf90_close, nf90_def_dim, nf90_put_att, define_ovar
nc_abort calls nf90_strerror
mpidrv_master calls create_landuse_cable_restart
cable_offline_driver calls create_landuse_cable_restart
mpi_driver calls mpidrv_master