CRU_GET_SUBDIURNAL_MET – CABLE
CRU_GET_SUBDIURNAL_MET Subroutine
92 statements
Source File
public subroutine CRU_GET_SUBDIURNAL_MET(CRU, MET, CurYear, ktau, kend, LastYearOfMet)
Uses
cable_def_types_mod
cable_IO_vars_module
casa_ncdf_module
cable_checks_module
CABLE_WEATHERGENERATOR
!! this only works with CANBERRA cable_driver, as ktau !!!! !! restarts on Jan 1 !!!!
$ if (WG%Temp(iland) > 2.5) then $ met%precip_sn(is:ie) = 0.0 $ elseif ((WG%Temp(iland) <= 2.5) .and. (WG%Temp(iland) > 2.0)) then $ met%precip_sn(is:ie) = 0.6 met%precip(is:ie) $ elseif ((WG%Temp(iland) <= 2.0) .and. (WG%Temp(iland) > 0.0)) then $ met%precip_sn(is:ie) = (1.0 - (54.62 - 0.2 (WG%Temp(iland) + 273.15)))* met%precip(is:ie) ! this facr can be > 1 !!! $ elseif (WG%Temp(iland) <= 0.0) then $ met%precip_sn(is:ie) = met%precip(is:ie) $ endif
Arguments
Type Intent Optional Attributes Name
type(CRU_TYPE) :: CRU
type(met_type) :: MET
integer, intent(in) :: CurYear
integer, intent(in) :: ktau
integer, intent(in) :: kend
logical, intent(in) :: LastYearOfMet
Calls
Called by
Contents
None
Call graph
cru_get_subdiurnal_met calls wgen_init, wgen_daily_constants, open_cru_met, doysod2ymdhms, cru_get_daily_met, wgen_subdiurnal_met, nf90_close, get_cru_ndep, get_cru_co2, handle_err
open_cru_met calls handle_err, cru_get_filename, nf90_inq_varid, nf90_open
doysod2ymdhms calls is_leapyear
cru_get_daily_met calls nf90_close, handle_err, cru_get_filename, nf90_inq_varid, nf90_get_var, nf90_inq_dimid, nf90_inquire_dimension, nf90_open
get_cru_ndep calls handle_err, nf90_inq_varid, nf90_get_var, nf90_open
get_cru_co2 calls get_unit
handle_err calls nf90_strerror
mpidrv_master calls cru_get_subdiurnal_met
cable_offline_driver calls cru_get_subdiurnal_met
mpi_driver calls mpidrv_master