HANDLE_ERR – CABLE
HANDLE_ERR Subroutine
11 statements
Source File
public subroutine HANDLE_ERR(status, msg)
Uses
netcdf
Arguments
Type Intent Optional Attributes Name
integer :: status
character(len=*), intent(in), optional :: msg
Calls
Called by
Contents
None
Call graph
handle_err calls nf90_strerror
open_cru_met calls handle_err
luc_expt_init calls handle_err, read_climatefile
cru_get_subdiurnal_met calls handle_err, open_cru_met, cru_get_daily_met, get_cru_ndep
write_landuse_casa_restart_nc calls handle_err
cru_get_daily_met calls handle_err
plume_get_daily_met calls handle_err
plume_mip_get_met calls handle_err, plume_get_daily_met, open_plume_met
read_luh2 calls handle_err
get_cru_ndep calls handle_err
cru_init calls handle_err
open_met_file calls handle_err
plume_mip_init calls handle_err
read_climatefile calls handle_err
load_parameters calls handle_err
open_plume_met calls handle_err
mpidrv_master calls luc_expt_init, cru_get_subdiurnal_met, write_landuse_casa_restart_nc, plume_mip_get_met, cru_init, open_met_file, plume_mip_init, load_parameters
cable_offline_driver calls luc_expt_init, cru_get_subdiurnal_met, write_landuse_casa_restart_nc, plume_mip_get_met, cru_init, open_met_file, plume_mip_init, load_parameters, lucdriver
lucdriver calls read_luh2
mpi_driver calls mpidrv_master