IS_CASA_TIME – CABLE
IS_CASA_TIME Function
42 statements
Source File
public function IS_CASA_TIME(iotype, yyyy, ktau, kstart, koffset, kend, ktauday, logn)
Uses
cable_common_module
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: iotype*5
integer, intent(in) :: yyyy
integer, intent(in) :: ktau
integer, intent(in) :: kstart
integer, intent(in) :: koffset
integer, intent(in) :: kend
integer, intent(in) :: ktauday
integer, intent(in) :: logn
Return Value logical
Called by
Contents
None
Call graph
mpidrv_master calls is_casa_time
cable_offline_driver calls is_casa_time
mpidrv_worker calls is_casa_time
mpi_driver calls mpidrv_master, mpidrv_worker