landuse_data – CABLE
landuse_data Subroutine
55 statements
Source File
subroutine landuse_data(mlon, mlat, landmask, arealand, luc_atransit, luc_fharvw, luc_xluh2cable)
Uses
landuse_constant
cable_abort_module
cable_common_module
cable_def_types_mod
netcdf
Arguments
Type Intent Optional Attributes Name
integer :: mlon
integer :: mlat
integer, dimension(mlon,mlat) :: landmask
real(kind=r_2), dimension(mland) :: arealand
real(kind=r_2), dimension(mland,mvmax,mvmax) :: luc_atransit
real(kind=r_2), dimension(mland,mharvw) :: luc_fharvw
real(kind=r_2), dimension(mland,mvmax,mstate) :: luc_xluh2cable
Calls
Called by
Contents
None
Call graph
landuse_data calls nf90_inq_dimid, nf90_get_var, nf90_inq_varid, nc_abort, nf90_inquire_dimension, nf90_close, nf90_open, landuse_getxluh2, landuse_getdata
nc_abort calls nf90_strerror
landuse_getxluh2 calls nf90_get_var, nf90_inq_varid, nf90_close, nf90_open
landuse_getdata calls nf90_get_var, nf90_inq_varid, nf90_close, nf90_open
mpidrv_master calls landuse_data
cable_offline_driver calls landuse_data
mpi_driver calls mpidrv_master