LUC_EXPT_INIT – CABLE
LUC_EXPT_INIT Subroutine
177 statements
Source File
public subroutine LUC_EXPT_INIT(LUC_EXPT)
$ STATUS = NF90_GET_VAR(Luc_expt%f_id(i), timID, tmp, & $ start=(/1,1,1/)) $ CALL HANDLE_ERR(STATUS, "Reading from "//LUC_EXPT%TransFile(i))
$ WHERE (LUC_EXPT%ivegp == 14) $ LUC_EXPT%prim_only = .TRUE. $ END WHERE
Arguments
Type Intent Optional Attributes Name
type(LUC_EXPT_TYPE), intent(inout) :: LUC_EXPT
Calls
Called by
Contents
None
Call graph
luc_expt_init calls get_unit, nf90_inq_dimid, nf90_inq_varid, nf90_get_var, nf90_inquire_dimension, nf90_open, handle_err, read_climatefile
handle_err calls nf90_strerror
read_climatefile calls nf90_inq_dimid, nf90_inq_varid, nf90_get_var, nf90_inquire_dimension, nf90_open, handle_err, nf90_close
mpidrv_master calls luc_expt_init
cable_offline_driver calls luc_expt_init
mpi_driver calls mpidrv_master