mpidrv_worker – CABLE
mpidrv_worker Subroutine
270 statements
Source File
public subroutine mpidrv_worker(comm)
Uses
POPmodule
CABLE_PLUME_MIP
cable_cbm_module
phenvariable
casadimension
cable_namelist_util
POP_Constants
cable_common_module
cable_input_module
cbl_soil_snow_init_special_module
POP_Types
casavariable
mpi
cable_def_types_mod
casa_ncdf_module
cable_IO_vars_module
cable_output_module
cable_climate_mod
vh_js !! vh_js !! suggest LALLOC should ulitmately be a switch in the .nml file Check for gswp run
$ idoy = mod(ktau/ktauday,365) $ IF(idoy==0) idoy=365 $ $ ! needed for CASA-CNP $ nyear =INT((kend-kstart+1)/(365*ktauday))
jhan this is insufficient testing. condition for spinup=.false. & we want CASA_dump.nc (spinConv=.true.) see if spinup (if conducting one) has converged:
Arguments
Type Intent Optional Attributes Name
integer :: comm
Calls
Called by
Contents
None
Call graph
mpidrv_worker calls mpi_comm_rank, find_extents, cable_climate, cbm, mpi_recv, mpi_send, sumcflux, mpi_bcast, mpi_comm_dup, is_leapyear, spec_init_soil_snow, is_casa_time, casa_feedback, bgcdriver, popdriver
find_extents calls mpi_get_address
cbm calls ruff_resist, fveg_mask, snow_aging, fsunlit_veg_mask, define_canopy, plantcarb, carbon_pl, define_air, fsunlit_mask, init_radiation, albedo, soil_snow, soilcarb
mpi_driver calls mpidrv_worker