PLUME_MIP_GET_MET – CABLE
PLUME_MIP_GET_MET Subroutine
77 statements
Source File
public subroutine PLUME_MIP_GET_MET(PLUME, MET, CurYear, ktau, kend, islast)
Uses
cable_def_types_mod
cable_IO_vars_module
casa_ncdf_module
cable_checks_module
CABLE_WEATHERGENERATOR
!! this only works with CANBERRA cable_driver, as ktau !!!! !! restarts on Jan 1 !!!!
$write(,) "met", met%precip(1), & $met%precip_sn (is:ie) , & $ met%fld (is:ie), & $ met%fsd (is:ie,1), & $ met%fsd (is:ie,2), & $ met%tk (is:ie) , & $ met%ua (is:ie) , & $ met%coszen (is:ie)
Arguments
Type Intent Optional Attributes Name
type(PLUME_MIP_TYPE) :: PLUME
type(met_type) :: MET
integer, intent(in) :: CurYear
integer, intent(in) :: ktau
integer, intent(in) :: kend
logical, intent(in) :: islast
Calls
Called by
Contents
None
Call graph
plume_mip_get_met calls wgen_init, plume_get_daily_met, wgen_daily_constants, doysod2ymdhms, get_plume_co2, wgen_subdiurnal_met, nf90_close, file_switch, open_plume_met, handle_err
plume_get_daily_met calls nf90_close, handle_err, nf90_get_var, nf90_inq_dimid, nf90_inq_varid, nf90_inquire_dimension, nf90_open, plume_get_filename
doysod2ymdhms calls is_leapyear
get_plume_co2 calls get_unit
open_plume_met calls handle_err, nf90_inq_varid, nf90_open, plume_get_filename, leap_day, nf90_get_att
handle_err calls nf90_strerror
mpidrv_master calls plume_mip_get_met
cable_offline_driver calls plume_mip_get_met
mpi_driver calls mpidrv_master