alloc_roughness_type – CABLE
alloc_roughness_type Subroutine
26 statements
Source File
public subroutine alloc_roughness_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(roughness_type), intent(inout) :: var
integer, intent(in) :: mp
Called by
Contents
None
Call graph
alloc_cbm_var calls alloc_roughness_type
allocate_cable_vars calls alloc_cbm_var
mpidrv_master calls alloc_cbm_var, load_parameters
load_parameters calls allocate_cable_vars
mpi_driver calls mpidrv_master
cable_offline_driver calls load_parameters