GET_UNIT – CABLE
GET_UNIT Subroutine
11 statements
Source File
public subroutine GET_UNIT(IUNIT)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: IUNIT
Called by
Contents
None
Call graph
get_plume_co2 calls get_unit
site_init calls get_unit
site_get_co2_ndep calls get_unit
luc_expt_init calls get_unit
cru_init calls get_unit
plume_mip_init calls get_unit
get_cru_co2 calls get_unit
plume_mip_get_met calls get_plume_co2
mpidrv_master calls luc_expt_init, cru_init, plume_mip_init, plume_mip_get_met, cru_get_subdiurnal_met
cru_get_subdiurnal_met calls get_cru_co2
cable_offline_driver calls site_init, site_get_co2_ndep, luc_expt_init, cru_init, plume_mip_init, plume_mip_get_met, cru_get_subdiurnal_met
mpi_driver calls mpidrv_master