load_parameters – CABLE
load_parameters Subroutine
123 statements
Source File
public subroutine load_parameters(met, air, ssnow, veg, climate, bgc, soil, canopy, rough, rad, sum_flux, bal, logn, vegparmnew, casabiome, casapool, casaflux, sum_casapool, sum_casaflux, casamet, casabal, phen, POP, spinup, EMSOIL, TFRZ, LUC_EXPT, POPLUC)
Uses
CABLE_LUC_EXPT
POPmodule
POPLUC_module
vh_js !! vh_js !!
Arguments
Type Intent Optional Attributes Name
type(met_type), intent(inout) :: met
type(air_type), intent(inout) :: air
type(soil_snow_type), intent(out) :: ssnow
type(veg_parameter_type), intent(out) :: veg
type(climate_type), intent(inout) :: climate
type(bgc_pool_type), intent(out) :: bgc
type(soil_parameter_type), intent(out) :: soil
type(canopy_type), intent(out) :: canopy
type(roughness_type), intent(out) :: rough
type(radiation_type), intent(out) :: rad
type(sum_flux_type), intent(out) :: sum_flux
type(balances_type), intent(out) :: bal
integer, intent(in) :: logn
logical, intent(in) :: vegparmnew
vh_js !!
type(casa_biome), intent(out) :: casabiome
type(casa_pool), intent(out) :: casapool
type(casa_flux), intent(out) :: casaflux
type(casa_pool), intent(out) :: sum_casapool
type(casa_flux), intent(out) :: sum_casaflux
type(casa_met), intent(out) :: casamet
type(casa_balance), intent(out) :: casabal
type(phen_variable), intent(out) :: phen
type(POP_TYPE), intent(inout) :: POP
logical, intent(in) :: spinup
vh_js !!
real, intent(in) :: EMSOIL
real, intent(in) :: TFRZ
type(LUC_EXPT_TYPE), intent(inout) :: LUC_EXPT
type(POPLUC_TYPE), intent(inout) :: POPLUC
Calls
Called by
Contents
None
Call graph
load_parameters calls nf90_inq_dimid, report_parameters, casa_readphen, nf90_open, pop_init, nc_abort, nf90_inquire_dimension, casa_init, handle_err, derived_parameters, write_cnp_params, pop_io, alloc_casavariable, allocate_cable_vars, get_default_params, alloc_phenvariable, write_default_params, casa_readbiome, get_restart_data, check_parameter_values, alloc_sum_casavariable, popluc_init
report_parameters calls cable_pft_params, cable_soil_params
nc_abort calls nf90_strerror
handle_err calls nf90_strerror
allocate_cable_vars calls alloc_cbm_var
get_default_params calls cable_pft_params, luc_expt_set_tiles, cable_soil_params
get_restart_data calls nf90_inq_dimid, nc_abort, nf90_inquire_dimension, nf90_get_var, nf90_inq_varid, nf90_close, readpar
alloc_cbm_var calls alloc_balances_type, alloc_roughness_type, alloc_met_type, alloc_radiation_type, alloc_soil_parameter_type, alloc_veg_parameter_type, alloc_canopy_type, alloc_soil_snow_type, alloc_air_type, alloc_sum_flux_type, alloc_climate_type
luc_expt_set_tiles calls 1166
mpidrv_master calls load_parameters
cable_offline_driver calls load_parameters
mpi_driver calls mpidrv_master