LUCdriver – CABLE
LUCdriver Subroutine
64 statements
Source File
subroutine LUCdriver(casabiome, casapool, casaflux, POP, LUC_EXPT, POPLUC, veg)
Uses
cable_carbon_module
CABLE_LUC_EXPT
casaparm
casadimension
cable_common_module
TypeDef
POP_Types
POPLUC_Types
cable_def_types_mod
cable_IO_vars_module
casa_ncdf_module
POPMODULE
casavariable
POPLUC_Module
Arguments
Type Intent Optional Attributes Name
type(casa_biome), intent(inout) :: casabiome
type(casa_pool), intent(inout) :: casapool
type(casa_flux), intent(inout) :: casaflux
type(POP_TYPE), intent(inout) :: POP
type(LUC_EXPT_TYPE), intent(inout) :: LUC_EXPT
type(POPLUC_TYPE), intent(inout) :: POPLUC
type(veg_parameter_type), intent(in) :: veg
Calls
Called by
Contents
None
Call graph
lucdriver calls read_luh2, popluc_weights_transfer, pop_init_single, poplucstep
read_luh2 calls nf90_get_var, handle_err
handle_err calls nf90_strerror
cable_offline_driver calls lucdriver