mpidrv_master – CABLE
mpidrv_master Subroutine
633 statements
Source File
public subroutine mpidrv_master(comm)
Uses
casa_cable
CABLE_PLUME_MIP
cable_cbm_module
landuse_constant
casadimension
cable_common_module
landuse_variable
casa_ncdf_module
cable_IO_vars_module
cable_climate_mod
CABLE_LUC_EXPT
phenvariable
cable_namelist_util
POP_Constants
cable_input_module
cable_output_module
cable_def_types_mod
casavariable
POP_Types
POPLUC_Types
casa_inout_module
cable_phys_constants_mod
mpi
POPLUC_Module
CABLE_CRU
cable_write_module
vh_js !! vh_js !! suggest LALLOC should ulitmately be a switch in the .nml file vh_js !! $ IF (CASAONLY .AND. IS_CASA_TIME("dread", yyyy, iktau, kstart, koffset, & $ kend, ktauday, logn)) THEN $ ! CLN READ FROM FILE INSTEAD ! $ WRITE(CYEAR,FMT="(I4)")CurYear + INT((ktau-kstart+koffset)/(LOY*ktauday)) $ ncfile = TRIM(casafile%c2cdumppath)//'c2c_'//CYEAR//'_dump.nc' $ casa_it = NINT(REAL(iktau / ktauday)) $ CALL read_casa_dump(ncfile, casamet, casaflux, casa_it, kend, .FALSE.) $ ENDIF
$ ! At first time step of year, set tile area according to updated LU areas $ IF (ktau == 1 .and. CABLE_USER%POPLUC) THEN $ CALL POPLUC_set_patchfrac(POPLUC,LUC_EXPT) $ ENDIF
$ IF (((.NOT.spinup).OR.(spinup.AND.spinConv)) .AND. & $ (IS_CASA_TIME("dwrit", yyyy, oktau, kstart, & $ koffset, kend, ktauday, logn))) THEN $ WRITE(CYEAR,FMT="(I4)") CurYear + INT((ktau-kstart)/(LOY*ktauday)) $ ncfile = TRIM(casafile%c2cdumppath)//'c2c_'//CYEAR//'_dump.nc' $ CALL write_casa_dump(ncfile, casamet , casaflux, idoy, & $ kend/ktauday) $ $ ENDIF
$ if (ktau == kend-1) PRINT, "time-space-averaged energy & water balances" $ if (ktau == kend-1) PRINT,"Ebal_tot[Wm-2], Wbal_tot[mm]", & $ sum(bal%ebal_tot)/mp/count_bal, sum(bal%wbal_tot)/mp/count_bal $ if (ktau == kend-1) PRINT, "time-space-averaged latent heat and net photosynthesis" $ if (ktau == kend-1) PRINT, "sum_fe[Wm-2], sum_fpn[umol/m2/s]", & $ new_sumfe/count_bal, new_sumfpn/count_bal
$ IF (CABLE_USER%CASA_DUMP_WRITE) THEN $ !CLN CHECK FOR LEAP YEAR $ WRITE(CYEAR,FMT="(I4)") CurYear + INT((ktau-kstart)/(LOY*ktauday)) $ ncfile = TRIM(casafile%c2cdumppath)//'c2c_'//CYEAR//'_dump.nc' $ CALL write_casa_dump(ncfile, casamet , casaflux, idoy, & $ kend/ktauday) $ $ ENDIF
$ CALL casa_poolout(ktau, veg, soil, casabiome, & $ casapool, casaflux, casamet, casabal, phen)
Arguments
Type Intent Optional Attributes Name
integer :: comm
Calls
Called by
Contents
None
Call graph
mpidrv_master calls find_extents, alloc_cbm_var, plume_mip_get_met, get_met_data, mpi_send, popluc_set_patchfrac, write_landuse_casa_restart_nc, mpi_bcast, is_leapyear, load_parameters, write_casa_dump, write_casa_restart_nc, landuse_data, create_new_gridinfo, landuse_deallocate_mp, nullify_write, close_met_file, write_luc_restart_nc, write_luc_output_nc, create_restart, luc_expt_init, mpi_abort, pop_luc_casa_transfer, pop_io, casa_fluxout, create_landuse_cable_restart, close_output_file, mpi_waitall, is_casa_time, patch, write_luc_output_grid_nc, write_climate_restart_nc, landuse_driver, open_output_file, cru_get_subdiurnal_met, write_output, write_casa_output_nc, open_met_file, plume_mip_init, cru_init, mpi_comm_dup
find_extents calls mpi_get_address
alloc_cbm_var calls alloc_radiation_type, alloc_balances_type, alloc_sum_flux_type, alloc_roughness_type, alloc_soil_parameter_type, alloc_soil_snow_type, alloc_air_type, alloc_met_type, alloc_veg_parameter_type, alloc_canopy_type, alloc_climate_type
plume_mip_get_met calls get_plume_co2, plume_get_daily_met, wgen_daily_constants, wgen_init, handle_err, nf90_close, open_plume_met, doysod2ymdhms, wgen_subdiurnal_met, file_switch
get_met_data calls is_leapyear, nf90_get_var, nc_abort, nf90_inquire_variable, rh_sh, sinbet
write_landuse_casa_restart_nc calls nf90_put_var, nf90_put_att, nf90_create, handle_err, nf90_close, nf90_def_var, nf90_redef, nf90_enddef, nf90_def_dim
load_parameters calls pop_io, nf90_inq_dimid, report_parameters, get_restart_data, casa_readphen, pop_init, nf90_open, nc_abort, nf90_inquire_dimension, check_parameter_values, handle_err, casa_init, derived_parameters, write_cnp_params, alloc_casavariable, allocate_cable_vars, get_default_params, alloc_phenvariable, write_default_params, casa_readbiome, alloc_sum_casavariable, popluc_init
landuse_data calls nf90_get_var, nf90_inq_dimid, nf90_open, landuse_getdata, nc_abort, nf90_inquire_dimension, landuse_getxluh2, nf90_close, nf90_inq_varid
create_new_gridinfo calls nf90_get_var, nf90_put_var, nf90_put_att, nf90_open, nc_abort, nf90_create, rangechk3, nf90_close, nf90_def_var, nf90_inq_varid, sort, rangechk2, nf90_enddef, nf90_def_dim
close_met_file calls nc_abort, nf90_close
create_restart calls nf90_put_var, nf90_put_att, nc_abort, nf90_create, nf90_close, nf90_def_var, write_ovar, nf90_redef, nf90_enddef, nf90_def_dim, define_ovar
luc_expt_init calls nf90_get_var, nf90_inq_dimid, nf90_open, read_climatefile, nf90_inquire_dimension, handle_err, nf90_inq_varid, get_unit
create_landuse_cable_restart calls nf90_put_var, nf90_put_att, nc_abort, nf90_create, nf90_close, nf90_def_var, write_ovar, nf90_redef, nf90_enddef, nf90_def_dim, define_ovar
close_output_file calls nc_abort, nf90_close
open_output_file calls nf90_put_var, nf90_put_att, nc_abort, nf90_create, nf90_def_var, write_ovar, nf90_redef, nf90_enddef, nf90_def_dim, define_ovar
cru_get_subdiurnal_met calls wgen_daily_constants, wgen_init, open_cru_met, handle_err, get_cru_co2, nf90_close, cru_get_daily_met, get_cru_ndep, doysod2ymdhms, wgen_subdiurnal_met
write_output calls is_leapyear, nf90_put_var, nf90_sync, nc_abort, energy_balance, mass_balance, write_ovar
open_met_file calls is_leapyear, nf90_get_var, nf90_inq_dimid, find_metvarid, nf90_open, nc_abort, nf90_inquire_dimension, ymdhms2doysod, handle_err, nf90_inquire_variable, nf90_inq_varid, nf90_get_att, doysod2ymdhms
plume_mip_init calls nf90_get_var, nf90_inq_dimid, nf90_open, nf90_inquire_dimension, handle_err, nf90_close, nf90_inq_varid, get_unit
cru_init calls nf90_get_var, nf90_inq_dimid, nf90_open, nf90_inquire_dimension, handle_err, nf90_close, nf90_inq_varid, get_unit
get_plume_co2 calls get_unit
plume_get_daily_met calls nf90_get_var, nf90_inq_dimid, nf90_open, nf90_inquire_dimension, handle_err, nf90_close, nf90_inq_varid, plume_get_filename
report_parameters calls cable_soil_params, cable_pft_params
get_restart_data calls nf90_get_var, nf90_inq_dimid, nc_abort, nf90_inquire_dimension, nf90_close, nf90_inq_varid, readpar
find_metvarid calls nf90_inq_varid
landuse_getdata calls nf90_get_var, nf90_open, nf90_close, nf90_inq_varid
read_climatefile calls nf90_get_var, nf90_inq_dimid, nf90_open, nf90_inquire_dimension, handle_err, nf90_close, nf90_inq_varid
nc_abort calls nf90_strerror
open_cru_met calls nf90_open, handle_err, nf90_inq_varid, cru_get_filename
ymdhms2doysod calls is_leapyear
handle_err calls nf90_strerror
landuse_getxluh2 calls nf90_get_var, nf90_open, nf90_close, nf90_inq_varid
get_cru_co2 calls get_unit
cru_get_daily_met calls nf90_get_var, nf90_inq_dimid, nf90_open, nf90_inquire_dimension, handle_err, nf90_close, nf90_inq_varid, cru_get_filename
open_plume_met calls nf90_open, handle_err, nf90_inq_varid, nf90_get_att, plume_get_filename, leap_day
allocate_cable_vars calls alloc_cbm_var
get_cru_ndep calls nf90_get_var, nf90_open, handle_err, nf90_inq_varid
doysod2ymdhms calls is_leapyear
get_default_params calls cable_soil_params, cable_pft_params, luc_expt_set_tiles
luc_expt_set_tiles calls 1166
mpi_driver calls mpidrv_master