cable_offline_driver – CABLE
cable_offline_driver Program
639 statements
Source File
Uses
CABLE_PLUME_MIP
casa_cable
cable_cbm_module
landuse_constant
casadimension
cable_common_module
landuse_variable
cable_IO_vars_module
casa_ncdf_module
cable_climate_mod
CABLE_LUC_EXPT
phenvariable
cable_namelist_util
cbl_soil_snow_init_special_module
POP_Constants
cable_input_module
cable_output_module
cable_def_types_mod
casavariable
POP_Types
POPLUC_Types
CABLE_site
casa_inout_module
cable_phys_constants_mod
POPLUC_Module
CABLE_CRU
cable_write_module
vh_js !!
vh_js !! vh_js !! vh_js !! suggest LALLOC should ulitmately be a switch in the .nml file $ IF (.NOT. spinup) THEN $ IF (spincasa) THEN $ spincasa = .FALSE. $ WRITE(,) "spinup == .FALSE. -> spincasa set to .F." $ WRITE(logn,*)"spinup == .FALSE. -> spincasa set to .F." $ ENDIF $ ENDIF $
!! INISTUFF
$ YearStart = CABLE_USER%YearStart $ YearEnd = CABLE_USER%YearEnd $ cable_user%CASA_SPIN_ENDYEAR
Checks where parameters and initialisations should be loaded from.
vh_js !! vh_js !!
$ do kk=1,mp $ if(canopy%fe(kk).NE.(canopy%fe(kk))) THEN $ write(,) 'fe nan', kk, ktau,met%qv(kk), met%precip(kk),met%precip_sn(kk), & $ met%fld(kk), met%fsd(kk,:), met%tk(kk), met%ua(kk), ssnow%potev(kk), met%pmb(kk), & $ canopy%ga(kk), ssnow%tgg(kk,:), canopy%fwsoil(kk) $ $ $ stop $ endif $ if (casaflux%cnpp(kk).NE. casaflux%cnpp(kk)) then $ write(,) 'npp nan', kk, ktau, casaflux%cnpp(kk) $ stop $ $ endif $ $ $ !if (canopy%fwsoil(kk).eq.0.0) then $ ! write(,) 'zero fwsoil', ktau, canopy%fpn(kk) $ !endif $ $ $ enddo
$ IF(MOD(ktau_tot, kend) .EQ. 0 .AND. ktau_Tot .GT. kend .AND. & $ YYYY.EQ. CABLE_USER%YearEnd .OR. (NRRRR .GT. 1 .AND. & $ RRRR.EQ. NRRRR)) THEN
Calls
Contents
Variables
kstart mloop LALLOC ktau ktau_tot kend koffset koffset_met ktauday idoy nyear casa_it YYYY RYEAR RRRR NRRRR ctime LOY count_sum_casa wlogn dels GSWP_MID dum str1 str2 str3 met air canopy rad rough bal ssnow climate soil veg sum_flux bgc casabiome casapool casaflux sum_casapool sum_casaflux casamet casabal phen POP POPLUC PLUME CRU site LUC_EXPT lucmp cyear ncfile vegparmnew spinup spinConv spincasa l_casacnp l_landuse l_laiFeedbk l_vcmaxFeedbk CASAONLY CALL1 SPINon delsoilM delsoilT Metyear Y LOYtmp delgwM soilMtemp soilTtemp GWtemp etime heat_cap_lower_limit i x kk m np ivt Ftrunk_sumbal Fnew_sumbal trunk_sumbal new_sumbal new_sumfpn new_sumfe c1 rhoch xk nkend ioerror count_bal mlon mlat mpx luc_atransit luc_fharvw luc_xluh2cable arealand landmask cstart cend nap patchfrac_new
Variables
Type Attributes Name Initial
integer, parameter :: kstart = 1
integer, parameter :: mloop = 30
integer :: LALLOC
integer :: ktau
integer :: ktau_tot
integer :: kend
integer :: koffset = 0
integer :: koffset_met = 0
integer :: ktauday
integer :: idoy
integer :: nyear
integer :: casa_it
integer :: YYYY
integer :: RYEAR
integer :: RRRR
integer :: NRRRR
integer :: ctime
integer :: LOY
integer :: count_sum_casa
integer :: wlogn = 10001
real :: dels
integer, DIMENSION(:,:), ALLOCATABLE :: GSWP_MID
character :: dum*9
character :: str1*9
character :: str2*9
character :: str3*9
type(met_type) :: met
type(air_type) :: air
type(canopy_type) :: canopy
type(radiation_type) :: rad
type(roughness_type) :: rough
type(balances_type) :: bal
type(soil_snow_type) :: ssnow
type(climate_type) :: climate
type(soil_parameter_type) :: soil
type(veg_parameter_type) :: veg
type(sum_flux_type) :: sum_flux
type(bgc_pool_type) :: bgc
type(casa_biome) :: casabiome
type(casa_pool) :: casapool
type(casa_flux) :: casaflux
type(casa_pool) :: sum_casapool
type(casa_flux) :: sum_casaflux
type(casa_met) :: casamet
type(casa_balance) :: casabal
type(phen_variable) :: phen
vh_js !!
type(POP_TYPE) :: POP
type(POPLUC_TYPE) :: POPLUC
type(PLUME_MIP_TYPE) :: PLUME
type(CRU_TYPE) :: CRU
type(site_TYPE) :: site
type(LUC_EXPT_TYPE) :: LUC_EXPT
type(landuse_mp) :: lucmp
character :: cyear*4
character :: ncfile*99
logical, SAVE :: vegparmnew = .FALSE.
logical, SAVE :: spinup = .FALSE.
logical, SAVE :: spinConv = .FALSE.
logical, SAVE :: spincasa = .FALSE.
logical, SAVE :: l_casacnp = .FALSE.
logical, SAVE :: l_landuse = .FALSE.
logical, SAVE :: l_laiFeedbk = .FALSE.
logical, SAVE :: l_vcmaxFeedbk = .FALSE.
logical, SAVE :: CASAONLY = .FALSE.
logical, SAVE :: CALL1 = .TRUE.
logical, SAVE :: SPINon = .TRUE.
real :: delsoilM
real :: delsoilT
integer :: Metyear
integer :: Y
integer :: LOYtmp
real :: delgwM = 1e-4
real, ALLOCATABLE, DIMENSION(:,:) :: soilMtemp
real, ALLOCATABLE, DIMENSION(:,:) :: soilTtemp
real, ALLOCATABLE, DIMENSION(:) :: GWtemp
real :: etime
real, allocatable :: heat_cap_lower_limit(:,:)
integer :: i
integer :: x
integer :: kk
integer :: m
integer :: np
integer :: ivt
character(len=30), parameter :: Ftrunk_sumbal = ".trunk_sumbal"
character(len=30), parameter :: Fnew_sumbal = "new_sumbal"
double precision :: trunk_sumbal = 0.0
double precision :: new_sumbal = 0.0
double precision :: new_sumfpn = 0.0
double precision :: new_sumfe = 0.0
real, ALLOCATABLE, SAVE :: c1(:,:)
real, ALLOCATABLE, SAVE :: rhoch(:,:)
real, ALLOCATABLE, SAVE :: xk(:,:)
integer :: nkend = 0
integer :: ioerror
integer :: count_bal = 0
integer :: mlon
integer :: mlat
integer :: mpx
real(kind=r_2), dimension(:,:,:), allocatable, save :: luc_atransit
real(kind=r_2), dimension(:,:), allocatable, save :: luc_fharvw
real(kind=r_2), dimension(:,:,:), allocatable, save :: luc_xluh2cable
real(kind=r_2), dimension(:), allocatable, save :: arealand
integer, dimension(:,:), allocatable, save :: landmask
integer, dimension(:), allocatable, save :: cstart
integer, dimension(:), allocatable, save :: cend
integer, dimension(:), allocatable, save :: nap
real(kind=r_2), dimension(:,:,:), allocatable, save :: patchfrac_new
Call graph
cable_offline_driver calls site_init, plume_mip_get_met, casa_cnpflux, get_met_data, popluc_set_patchfrac, sumcflux, write_landuse_casa_restart_nc, is_leapyear, load_parameters, zero_sum_casa, spec_init_soil_snow, write_casa_dump, write_casa_restart_nc, landuse_data, create_new_gridinfo, landuse_deallocate_mp, nullify_write, spincasacnp, cable_climate, close_met_file, write_luc_restart_nc, get_namelist_file_name, read_casa_dump, popdriver, write_luc_output_nc, create_restart, preparefiles, luc_expt_init, climate_init, cbm, pop_luc_casa_transfer, casa_fluxout, pop_io, close_output_file, create_landuse_cable_restart, casaonly_luc, is_casa_time, bgcdriver, lucdriver, landuse_driver, write_climate_restart_nc, open_output_file, cru_get_subdiurnal_met, site_get_co2_ndep, update_sum_casa, write_output, plume_mip_init, open_met_file, cru_init, read_climate_restart_nc, casa_feedback, write_casa_output_nc
site_init calls get_unit
plume_mip_get_met calls plume_get_daily_met, wgen_daily_constants, nf90_close, open_plume_met, doysod2ymdhms, get_plume_co2, wgen_init, handle_err, wgen_subdiurnal_met, file_switch
get_met_data calls is_leapyear, nc_abort, nf90_inquire_variable, rh_sh, nf90_get_var, sinbet
write_landuse_casa_restart_nc calls nf90_create, nf90_close, nf90_put_var, handle_err, nf90_enddef, nf90_put_att, nf90_def_var, nf90_redef, nf90_def_dim
load_parameters calls pop_io, nf90_inq_dimid, alloc_casavariable, get_restart_data, popluc_init, nc_abort, derived_parameters, check_parameter_values, alloc_phenvariable, write_default_params, casa_readphen, nf90_open, handle_err, casa_init, casa_readbiome, alloc_sum_casavariable, report_parameters, pop_init, nf90_inquire_dimension, write_cnp_params, allocate_cable_vars, get_default_params
landuse_data calls nf90_inq_dimid, nf90_close, nc_abort, nf90_get_var, nf90_open, nf90_inq_varid, landuse_getdata, nf90_inquire_dimension, landuse_getxluh2
create_new_gridinfo calls nf90_create, nf90_close, sort, nc_abort, rangechk2, nf90_get_var, nf90_put_var, nf90_open, rangechk3, nf90_inq_varid, nf90_enddef, nf90_put_att, nf90_def_var, nf90_def_dim
close_met_file calls nf90_close, nc_abort
create_restart calls nf90_create, nf90_close, nc_abort, write_ovar, define_ovar, nf90_put_var, nf90_enddef, nf90_put_att, nf90_def_var, nf90_redef, nf90_def_dim
preparefiles calls renamefiles
luc_expt_init calls nf90_inq_dimid, get_unit, nf90_get_var, nf90_open, read_climatefile, handle_err, nf90_inq_varid, nf90_inquire_dimension
cbm calls snow_aging, albedo, define_canopy, soil_snow, ruff_resist, plantcarb, define_air, soilcarb, fveg_mask, carbon_pl, fsunlit_mask, fsunlit_veg_mask, init_radiation
close_output_file calls nf90_close, nc_abort
create_landuse_cable_restart calls nf90_create, nf90_close, nc_abort, write_ovar, define_ovar, nf90_put_var, nf90_enddef, nf90_put_att, nf90_def_var, nf90_redef, nf90_def_dim
lucdriver calls popluc_weights_transfer, read_luh2, poplucstep, pop_init_single
open_output_file calls nf90_create, nc_abort, write_ovar, define_ovar, nf90_put_var, nf90_enddef, nf90_put_att, nf90_def_var, nf90_redef, nf90_def_dim
cru_get_subdiurnal_met calls wgen_daily_constants, open_cru_met, nf90_close, get_cru_ndep, doysod2ymdhms, wgen_init, get_cru_co2, handle_err, wgen_subdiurnal_met, cru_get_daily_met
site_get_co2_ndep calls get_unit
write_output calls is_leapyear, nc_abort, write_ovar, nf90_put_var, mass_balance, nf90_sync, energy_balance
plume_mip_init calls nf90_inq_dimid, nf90_close, get_unit, nf90_get_var, nf90_open, handle_err, nf90_inq_varid, nf90_inquire_dimension
open_met_file calls is_leapyear, nf90_inq_dimid, ymdhms2doysod, nf90_get_att, doysod2ymdhms, nc_abort, nf90_inquire_variable, nf90_get_var, find_metvarid, nf90_open, handle_err, nf90_inq_varid, nf90_inquire_dimension
cru_init calls nf90_inq_dimid, nf90_close, get_unit, nf90_get_var, nf90_open, handle_err, nf90_inq_varid, nf90_inquire_dimension
plume_get_daily_met calls nf90_inq_dimid, nf90_close, nf90_get_var, nf90_open, handle_err, nf90_inq_varid, nf90_inquire_dimension, plume_get_filename
open_cru_met calls nf90_open, handle_err, nf90_inq_varid, cru_get_filename
ymdhms2doysod calls is_leapyear
get_cru_ndep calls nf90_get_var, nf90_open, handle_err, nf90_inq_varid
open_plume_met calls nf90_get_att, nf90_open, handle_err, nf90_inq_varid, plume_get_filename, leap_day
read_luh2 calls nf90_get_var, handle_err
get_restart_data calls nf90_inq_dimid, nf90_close, nc_abort, nf90_get_var, nf90_inq_varid, nf90_inquire_dimension, readpar
doysod2ymdhms calls is_leapyear
get_plume_co2 calls get_unit
nc_abort calls nf90_strerror
get_cru_co2 calls get_unit
find_metvarid calls nf90_inq_varid
read_climatefile calls nf90_inq_dimid, nf90_close, nf90_get_var, nf90_open, handle_err, nf90_inq_varid, nf90_inquire_dimension
handle_err calls nf90_strerror
report_parameters calls cable_pft_params, cable_soil_params
landuse_getdata calls nf90_close, nf90_get_var, nf90_open, nf90_inq_varid
landuse_getxluh2 calls nf90_close, nf90_get_var, nf90_open, nf90_inq_varid
cru_get_daily_met calls nf90_inq_dimid, nf90_close, nf90_get_var, nf90_open, handle_err, nf90_inq_varid, nf90_inquire_dimension, cru_get_filename
allocate_cable_vars calls alloc_cbm_var
get_default_params calls cable_pft_params, cable_soil_params, luc_expt_set_tiles
alloc_cbm_var calls alloc_balances_type, alloc_roughness_type, alloc_met_type, alloc_radiation_type, alloc_soil_parameter_type, alloc_veg_parameter_type, alloc_canopy_type, alloc_soil_snow_type, alloc_air_type, alloc_sum_flux_type, alloc_climate_type
luc_expt_set_tiles calls 1166