mpi_driver – CABLE
mpi_driver Program
27 statements
Source File
Uses
cable_namelist_util
mpi
cable_mpiworker
cable_mpimaster
cable_mpicommon
Calls
Contents
Variables
comm np rank ierr etime
Variables
Type Attributes Name Initial
integer :: comm
integer :: np
integer :: rank
integer :: ierr
real :: etime
Call graph
mpi_driver calls mpi_comm_size, mpidrv_master, mpi_abort, mpi_comm_rank, mpi_init, mpi_comm_dup, get_namelist_file_name, mpidrv_worker, mpi_finalize
mpidrv_master calls mpi_abort, mpi_comm_dup, find_extents, alloc_cbm_var, plume_mip_get_met, get_met_data, mpi_send, popluc_set_patchfrac, write_landuse_casa_restart_nc, mpi_bcast, is_leapyear, load_parameters, write_casa_dump, write_casa_restart_nc, landuse_data, create_new_gridinfo, landuse_deallocate_mp, nullify_write, close_met_file, write_luc_restart_nc, write_luc_output_nc, create_restart, luc_expt_init, pop_luc_casa_transfer, pop_io, casa_fluxout, create_landuse_cable_restart, close_output_file, mpi_waitall, is_casa_time, patch, write_luc_output_grid_nc, write_climate_restart_nc, landuse_driver, open_output_file, cru_get_subdiurnal_met, write_output, write_casa_output_nc, open_met_file, plume_mip_init, cru_init
mpidrv_worker calls mpi_comm_rank, mpi_comm_dup, find_extents, mpi_send, sumcflux, mpi_bcast, is_leapyear, spec_init_soil_snow, cable_climate, popdriver, mpi_recv, cbm, is_casa_time, bgcdriver, casa_feedback
find_extents calls mpi_get_address
alloc_cbm_var calls alloc_roughness_type, alloc_soil_parameter_type, alloc_balances_type, alloc_air_type, alloc_sum_flux_type, alloc_met_type, alloc_veg_parameter_type, alloc_radiation_type, alloc_soil_snow_type, alloc_canopy_type, alloc_climate_type
plume_mip_get_met calls plume_get_daily_met, wgen_daily_constants, nf90_close, open_plume_met, doysod2ymdhms, get_plume_co2, wgen_init, handle_err, wgen_subdiurnal_met, file_switch
get_met_data calls is_leapyear, nc_abort, nf90_inquire_variable, rh_sh, nf90_get_var, sinbet
write_landuse_casa_restart_nc calls nf90_create, nf90_close, nf90_put_var, handle_err, nf90_enddef, nf90_put_att, nf90_def_var, nf90_redef, nf90_def_dim
load_parameters calls pop_io, nf90_inq_dimid, alloc_casavariable, get_restart_data, popluc_init, nc_abort, derived_parameters, check_parameter_values, alloc_phenvariable, write_default_params, casa_readphen, nf90_open, handle_err, casa_init, casa_readbiome, alloc_sum_casavariable, report_parameters, pop_init, nf90_inquire_dimension, write_cnp_params, allocate_cable_vars, get_default_params
landuse_data calls nf90_inq_dimid, nf90_close, nc_abort, nf90_get_var, nf90_open, nf90_inq_varid, landuse_getdata, nf90_inquire_dimension, landuse_getxluh2
create_new_gridinfo calls nf90_create, nf90_close, sort, nc_abort, rangechk2, nf90_get_var, nf90_put_var, nf90_open, rangechk3, nf90_inq_varid, nf90_enddef, nf90_put_att, nf90_def_var, nf90_def_dim
close_met_file calls nf90_close, nc_abort
create_restart calls nf90_create, nf90_close, nc_abort, write_ovar, define_ovar, nf90_put_var, nf90_enddef, nf90_put_att, nf90_def_var, nf90_redef, nf90_def_dim
luc_expt_init calls nf90_inq_dimid, get_unit, nf90_get_var, nf90_open, read_climatefile, handle_err, nf90_inq_varid, nf90_inquire_dimension
create_landuse_cable_restart calls nf90_create, nf90_close, nc_abort, write_ovar, define_ovar, nf90_put_var, nf90_enddef, nf90_put_att, nf90_def_var, nf90_redef, nf90_def_dim
close_output_file calls nf90_close, nc_abort
cbm calls snow_aging, albedo, define_canopy, soil_snow, ruff_resist, plantcarb, define_air, soilcarb, fveg_mask, carbon_pl, fsunlit_mask, fsunlit_veg_mask, init_radiation
open_output_file calls nf90_create, nc_abort, write_ovar, define_ovar, nf90_put_var, nf90_enddef, nf90_put_att, nf90_def_var, nf90_redef, nf90_def_dim
cru_get_subdiurnal_met calls wgen_daily_constants, open_cru_met, nf90_close, get_cru_ndep, doysod2ymdhms, wgen_init, get_cru_co2, handle_err, wgen_subdiurnal_met, cru_get_daily_met
write_output calls is_leapyear, nc_abort, write_ovar, nf90_put_var, mass_balance, nf90_sync, energy_balance
open_met_file calls is_leapyear, nf90_inq_dimid, ymdhms2doysod, nf90_get_att, doysod2ymdhms, nc_abort, nf90_inquire_variable, nf90_get_var, find_metvarid, nf90_open, handle_err, nf90_inq_varid, nf90_inquire_dimension
plume_mip_init calls nf90_inq_dimid, nf90_close, get_unit, nf90_get_var, nf90_open, handle_err, nf90_inq_varid, nf90_inquire_dimension
cru_init calls nf90_inq_dimid, nf90_close, get_unit, nf90_get_var, nf90_open, handle_err, nf90_inq_varid, nf90_inquire_dimension
plume_get_daily_met calls nf90_inq_dimid, nf90_close, nf90_get_var, nf90_open, handle_err, nf90_inq_varid, nf90_inquire_dimension, plume_get_filename
open_cru_met calls nf90_open, handle_err, nf90_inq_varid, cru_get_filename
ymdhms2doysod calls is_leapyear
open_plume_met calls nf90_get_att, nf90_open, handle_err, nf90_inq_varid, plume_get_filename, leap_day
get_cru_ndep calls nf90_get_var, nf90_open, handle_err, nf90_inq_varid
get_restart_data calls nf90_inq_dimid, nf90_close, nc_abort, nf90_get_var, nf90_inq_varid, nf90_inquire_dimension, readpar
doysod2ymdhms calls is_leapyear
get_plume_co2 calls get_unit
nc_abort calls nf90_strerror
get_cru_co2 calls get_unit
find_metvarid calls nf90_inq_varid
read_climatefile calls nf90_inq_dimid, nf90_close, nf90_get_var, nf90_open, handle_err, nf90_inq_varid, nf90_inquire_dimension
handle_err calls nf90_strerror
report_parameters calls cable_pft_params, cable_soil_params
landuse_getdata calls nf90_close, nf90_get_var, nf90_open, nf90_inq_varid
landuse_getxluh2 calls nf90_close, nf90_get_var, nf90_open, nf90_inq_varid
cru_get_daily_met calls nf90_inq_dimid, nf90_close, nf90_get_var, nf90_open, handle_err, nf90_inq_varid, nf90_inquire_dimension, cru_get_filename
allocate_cable_vars calls alloc_cbm_var
get_default_params calls cable_pft_params, cable_soil_params, luc_expt_set_tiles
luc_expt_set_tiles calls 1166