alloc_cbm_var – CABLE
alloc_cbm_var Interface
3 statements
Source File
public interface alloc_cbm_var
Calls
Called by
Contents
Module Procedures
alloc_balances_type alloc_soil_parameter_type alloc_soil_snow_type alloc_veg_parameter_type alloc_canopy_type alloc_radiation_type alloc_roughness_type alloc_air_type alloc_met_type alloc_sum_flux_type alloc_bgc_pool_type alloc_climate_type
Module Procedures
public subroutine alloc_balances_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(balances_type), intent(inout) :: var
integer, intent(in) :: mp
public subroutine alloc_soil_parameter_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(soil_parameter_type), intent(inout) :: var
integer, intent(in) :: mp
public subroutine alloc_soil_snow_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(soil_snow_type), intent(inout) :: var
integer, intent(in) :: mp
public subroutine alloc_veg_parameter_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(veg_parameter_type), intent(inout) :: var
integer, intent(in) :: mp
public subroutine alloc_canopy_type(var, mp)
vh_js !! liiter resistances to heat and vapour transfer
Arguments
Type Intent Optional Attributes Name
type(canopy_type), intent(inout) :: var
integer, intent(in) :: mp
public subroutine alloc_radiation_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(radiation_type), intent(inout) :: var
integer, intent(in) :: mp
public subroutine alloc_roughness_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(roughness_type), intent(inout) :: var
integer, intent(in) :: mp
public subroutine alloc_air_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(air_type), intent(inout) :: var
integer, intent(in) :: mp
public subroutine alloc_met_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(met_type), intent(inout) :: var
integer, intent(in) :: mp
public subroutine alloc_sum_flux_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(sum_flux_type), intent(inout) :: var
integer, intent(in) :: mp
private subroutine alloc_bgc_pool_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(bgc_pool_type), intent(inout) :: var
integer, intent(in) :: mp
public subroutine alloc_climate_type(var, mp)
Arguments
Type Intent Optional Attributes Name
type(climate_type), intent(inout) :: var
integer, intent(in) :: mp
Call graph
alloc_cbm_var calls alloc_balances_type, alloc_roughness_type, alloc_met_type, alloc_radiation_type, alloc_soil_parameter_type, alloc_veg_parameter_type, alloc_canopy_type, alloc_soil_snow_type, alloc_air_type, alloc_sum_flux_type, alloc_climate_type
allocate_cable_vars calls alloc_cbm_var
mpidrv_master calls alloc_cbm_var, load_parameters
load_parameters calls allocate_cable_vars
mpi_driver calls mpidrv_master
cable_offline_driver calls load_parameters